# Run linting and basic file format checks

name: Lint

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo content
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Test with ruff
      shell: bash
      run: |
        pip install ruff
        python -m ruff check .
        python -m ruff format . --check